import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: "#E8F1FA",
    paddingHorizontal: 20,
    paddingTop: 30,
    gap: 30,
  },
  titleBox: {
    alignItems: "center",
  },
  title: {
    fontSize: 26,
    fontWeight: "900",
    color: "#011F5B",
    textAlign: "center",
    textShadowColor: "#999",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 3,
    borderBottomWidth: 2,
    borderBottomColor: "#011F5B",
    paddingBottom: 4,
  },
  header: {
    fontSize: 22,
    fontWeight: "700",
    color: "#011F5B",
    marginBottom: "20",
  },
  text: {
    fontSize: 18,
    color: "#011F5B",
  },
  image: {
    width: 300,  
    height: 180, 
    borderWidth: 2,
    borderColor: "#000",
    borderRadius: 10,
  },
  codeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  circle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 6,
    marginBottom: 10,
  },
  countText: {
    fontSize: 22,
    fontWeight: "700",
  },
  helpButton: {
    position: "absolute",
    top: 80,         
    right: 30,
    backgroundColor: "#F8D7DA",
    borderRadius: 30, 
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",

    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3, 
  },
});
